### ISSUE TITLE
BUG - Negative values deleting old entries

### ISSUE THREAD

**Issue by stfnrpplngr** [janid/equidopa-dist#1]
Thank you for this valuable resource. Your online-calculator is a great help computing LEDD values.

Using the tool, I occasionally have to delete entries or correct some values. Doing so results in negative LED values. That obviously appears to be a severe BUG. Inserting the same values, thus, can lead to different results, because deleted entries are still subtracted from the total summary.

![BUG_LEDD_onlinecalc](https://user-images.githubusercontent.com/20129752/130960100-ab7d1bcc-184c-4374-8b7a-a57acf340c89.gif)

**Comment by janid** [comment]
Hello, thank you for your valuable feedback! I fixed the issue. If there is anything else, please let me know, we appreciate any feedback we can get.
